---
- name: Create user
  user:
    name: "{{ created_username }}"
    state: present
    groups: sudo, docker
    append: yes

- name: Set up sudoers
  lineinfile:
    path: /etc/sudoers
    line: "{{ created_username }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: 'visudo -cf %s'

- name: Set up ssh keys
  ansible.posix.authorized_key:
    user: "{{ created_username }}"
    state: present
    key: "{{ ssh_public_key }}"